#!/usr/bin/env bash
# =============================================================================
#  kuma-push.sh  —  Uptime Kuma heartbeat  v1.0
# =============================================================================
#  Installs a small curl-based push script and schedules it on Ubuntu via
#  cron or a systemd timer so Uptime Kuma sees this host as up.
#
#  Usage:
#    sudo ./kuma-push.sh                   First-time install
#    sudo ./kuma-push.sh --install         Same as above
#    sudo ./kuma-push.sh --config          Re-run configuration wizard
#    sudo ./kuma-push.sh --status          Show scheduler status & last run
#    sudo ./kuma-push.sh --test            Send one push now
#    sudo ./kuma-push.sh --start           Enable/start the systemd timer
#    sudo ./kuma-push.sh --stop            Stop the systemd timer
#    sudo ./kuma-push.sh --restart         Restart the systemd timer
#         ./kuma-push.sh --help            Show this help
#    sudo ./kuma-push.sh --uninstall       Remove script, cron, and timer
# =============================================================================
#  Version history:
#    1.0  — Initial Ubuntu installer (interactive wizard, cron or systemd)
# =============================================================================
#  Dependencies (auto-installed if missing):
#    - curl           HTTPS push to Uptime Kuma
#
#  Pre-requisites (manual setup required):
#    - An Uptime Kuma Push monitor and its push URL / token
#    - Outbound HTTPS from this host to the Kuma instance
# =============================================================================

VERSION="1.0"
PUSH_SCRIPT="/usr/local/bin/kuma-push.sh"
CRON_TAG="# kuma-push"
SERVICE_NAME="kuma-push"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
TIMER_FILE="/etc/systemd/system/${SERVICE_NAME}.timer"
CONFIG_DIR="/etc/kuma-push"
CONFIG_FILE="${CONFIG_DIR}/kuma-push.conf"

RED='\033[0;31m';  GREEN='\033[0;32m';  YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m';  BOLD='\033[1m';  NC='\033[0m'
info()   { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()     { echo -e "${GREEN}[ OK ]${NC}  $*"; }
warn()   { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()  { echo -e "${RED}[ERR ]${NC}  $*" >&2; }
header() { echo -e "\n${BOLD}${BLUE}── $* ──────────────────────────────────────${NC}"; }
die()    { error "$*"; exit 1; }

require_root() {
    [[ $EUID -eq 0 ]] || die "Run as root:  sudo $0 ${1:-}"
}

load_config() {
    [[ -f "$CONFIG_FILE" ]] || return 1
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
}

prompt_value() {
    local label="$1" default="${2-}"
    local ps="  ${label}"
    [[ -n "$default" ]] && ps+=" [${CYAN}${default}${NC}]"
    echo -en "${ps}: "
    read -r REPLY || REPLY=""
    [[ -z "$REPLY" ]] && REPLY="$default"
}

prompt_choice() {
    local label="$1" default="$3"
    local -a choices=($2)
    local i=1 ps="  ${label} ("
    for c in "${choices[@]}"; do ps+="${i}) ${c}  "; i=$((i+1)); done
    echo -en "${ps}) [${CYAN}${default}${NC}]: "
    read -r REPLY || REPLY=""
    if [[ "$REPLY" =~ ^[0-9]+$ ]] && [ "$REPLY" -ge 1 ] && [ "$REPLY" -le "${#choices[@]}" ]; then
        REPLY="${choices[$((REPLY-1))]}"
    fi
    [[ -z "$REPLY" ]] && REPLY="$default"
}

ensure_curl() {
    header "Checking dependencies"
    if command -v curl >/dev/null 2>&1; then
        ok "curl  ($(curl --version | head -1))"
        return
    fi
    warn "curl missing — installing"
    apt-get update -qq || warn "apt-get update failed — trying anyway"
    apt-get install -y curl || die "Failed to install curl"
    ok "curl installed"
}

write_config() {
    header "Writing configuration"
    mkdir -p "$CONFIG_DIR" || die "Cannot create $CONFIG_DIR"
    chmod 750 "$CONFIG_DIR"
    cat > "$CONFIG_FILE" <<CONF
# =============================================================================
#  Uptime Kuma push — Configuration
#  Re-run:  sudo $0 --config
# =============================================================================
KUMA_PUSH_URL="${KUMA_PUSH_URL}"
KUMA_MSG="${KUMA_MSG}"
KUMA_INTERVAL="${KUMA_INTERVAL}"
KUMA_SCHEDULER="${KUMA_SCHEDULER}"
CONF
    chmod 640 "$CONFIG_FILE"
    ok "Config written → ${CONFIG_FILE}"
}

write_push_script() {
    header "Installing push script"
    local encoded_msg
    encoded_msg="$(printf '%s' "$KUMA_MSG" | sed 's/ /%20/g; s/&/%26/g')"
    cat > "$PUSH_SCRIPT" <<EOF
#!/bin/sh
# =============================================================================
#  kuma-push.sh  —  generated by kuma-push installer v${VERSION}
# =============================================================================
curl -fsS --max-time 15 \\
  "${KUMA_PUSH_URL}?status=up&msg=${encoded_msg}&ping=" \\
  >/dev/null 2>&1
EOF
    chmod 700 "$PUSH_SCRIPT"
    ok "Push script → ${PUSH_SCRIPT}"
}

remove_cron() {
    local tmp
    tmp="$(mktemp)"
    crontab -l 2>/dev/null | grep -v "$CRON_TAG" | grep -v "$PUSH_SCRIPT" >"$tmp" || true
    crontab "$tmp" 2>/dev/null || true
    rm -f "$tmp"
}

cron_expr() {
    local m="$1"
    if [[ "$m" -eq 1 ]]; then
        echo "* * * * *"
    elif [[ $((60 % m)) -eq 0 ]]; then
        echo "*/$m * * * *"
    else
        warn "cron cannot do every ${m}m cleanly — using every minute"
        echo "* * * * *"
    fi
}

install_cron() {
    header "Installing cron job"
    remove_systemd_units
    remove_cron
    local expr tmp
    expr="$(cron_expr "$KUMA_INTERVAL")"
    tmp="$(mktemp)"
    crontab -l 2>/dev/null >"$tmp" || true
    echo "$expr $PUSH_SCRIPT $CRON_TAG" >>"$tmp"
    crontab "$tmp" || die "Failed to install crontab"
    rm -f "$tmp"
    ok "Root crontab: $expr $PUSH_SCRIPT"
}

remove_systemd_units() {
    systemctl disable --now "${SERVICE_NAME}.timer" >/dev/null 2>&1 || true
    rm -f "$SERVICE_FILE" "$TIMER_FILE"
    systemctl daemon-reload >/dev/null 2>&1 || true
}

install_systemd() {
    header "Installing systemd timer"
    remove_cron
    cat > "$SERVICE_FILE" <<SVC
[Unit]
Description=Uptime Kuma push heartbeat
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${PUSH_SCRIPT}
SVC

    cat > "$TIMER_FILE" <<TMR
[Unit]
Description=Run Uptime Kuma push every ${KUMA_INTERVAL} minute(s)

[Timer]
OnBootSec=30s
OnUnitActiveSec=${KUMA_INTERVAL}min
AccuracySec=1s
Persistent=true

[Install]
WantedBy=timers.target
TMR

    systemctl daemon-reload
    systemctl enable --now "${SERVICE_NAME}.timer" || die "Failed to enable timer"
    ok "Timer ${SERVICE_NAME}.timer enabled (every ${KUMA_INTERVAL}m)"
}

apply_scheduler() {
    case "$KUMA_SCHEDULER" in
        cron)    install_cron ;;
        systemd) install_systemd ;;
        *)       die "Unknown scheduler: $KUMA_SCHEDULER" ;;
    esac
}

prompt_config() {
    header "Configuration wizard"
    local def_url="${KUMA_PUSH_URL:-}"
    local def_msg="${KUMA_MSG:-$(hostname -s)}"
    local def_int="${KUMA_INTERVAL:-1}"
    local def_sched="${KUMA_SCHEDULER:-systemd}"

    echo
    echo -e "  ${YELLOW}Press ENTER to accept [defaults].${NC}"
    echo
    echo    "  Push URL only — no ?status= query string."
    echo    "  Example: https://kuma.example.com/api/push/YOURTOKEN"
    echo
    prompt_value "Kuma push URL" "$def_url"; KUMA_PUSH_URL="${REPLY%%\?*}"
    [[ -n "$KUMA_PUSH_URL" ]] || die "Push URL is required"
    prompt_value "Message (msg=)" "$def_msg"; KUMA_MSG="$REPLY"
    prompt_value "Interval in minutes" "$def_int"; KUMA_INTERVAL="$REPLY"
    [[ "$KUMA_INTERVAL" =~ ^[1-9][0-9]*$ ]] || die "Interval must be a positive integer"
    prompt_choice "Scheduler" "systemd cron" "$def_sched"; KUMA_SCHEDULER="$REPLY"
    write_config
}

cmd_install() {
    require_root --install
    echo
    echo -e "${BOLD}${BLUE}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${BLUE}║   Uptime Kuma push — Installer  v${VERSION}          ║${NC}"
    echo -e "${BOLD}${BLUE}╚══════════════════════════════════════════════╝${NC}"
    echo
    ensure_curl
    if [[ -f "$CONFIG_FILE" ]]; then
        info "Config exists — skipping wizard.  Use  sudo $0 --config  to reconfigure."
        load_config || die "Could not read $CONFIG_FILE"
    else
        prompt_config
    fi
    write_push_script
    apply_scheduler
    echo
    echo -e "${GREEN}${BOLD}Installation complete!${NC}"
    echo -e "  Script  : ${CYAN}${PUSH_SCRIPT}${NC}"
    echo -e "  Config  : ${CYAN}${CONFIG_FILE}${NC}"
    echo -e "  Test    : ${CYAN}sudo $0 --test${NC}"
    echo -e "  Status  : ${CYAN}sudo $0 --status${NC}"
    echo
}

cmd_config() {
    require_root --config
    load_config || true
    prompt_config
    write_push_script
    apply_scheduler
    ok "Reconfiguration complete."
}

cmd_status() {
    header "Configuration: ${CONFIG_FILE}"
    if [[ -f "$CONFIG_FILE" ]]; then
        load_config
        echo -e "  URL       = ${CYAN}${KUMA_PUSH_URL}${NC}"
        echo -e "  Message   = ${CYAN}${KUMA_MSG}${NC}"
        echo -e "  Interval  = ${CYAN}${KUMA_INTERVAL}m${NC}"
        echo -e "  Scheduler = ${CYAN}${KUMA_SCHEDULER}${NC}"
    else
        warn "Config not found. Run: sudo $0 --install"
    fi

    header "Push script"
    if [[ -x "$PUSH_SCRIPT" ]]; then
        ok "$PUSH_SCRIPT"
    else
        warn "Not installed: $PUSH_SCRIPT"
    fi

    header "Scheduler"
    if [[ -f "$TIMER_FILE" ]]; then
        systemctl status "${SERVICE_NAME}.timer" --no-pager -l 2>/dev/null || warn "Timer not active"
        systemctl list-timers "${SERVICE_NAME}.timer" --no-pager 2>/dev/null || true
    fi
    if crontab -l 2>/dev/null | grep -q "$CRON_TAG\|$PUSH_SCRIPT"; then
        echo
        info "Root crontab:"
        crontab -l 2>/dev/null | grep "$CRON_TAG\|$PUSH_SCRIPT" || true
    fi
    echo
}

cmd_test() {
    require_root --test
    header "Sending a test push"
    [[ -x "$PUSH_SCRIPT" ]] || die "Push script missing. Run: sudo $0 --install"
    if "$PUSH_SCRIPT"; then
        ok "curl exited 0 — check Uptime Kuma for the heartbeat"
    else
        die "Push failed — check URL/token and outbound HTTPS"
    fi
}

cmd_start() {
    require_root --start
    [[ -f "$TIMER_FILE" ]] || die "No systemd timer. Install with scheduler=systemd."
    systemctl enable --now "${SERVICE_NAME}.timer" && ok "Timer started." || die "Failed."
}

cmd_stop() {
    require_root --stop
    systemctl stop "${SERVICE_NAME}.timer" 2>/dev/null && ok "Timer stopped." || warn "Timer was not running."
}

cmd_restart() {
    require_root --restart
    [[ -f "$TIMER_FILE" ]] || die "No systemd timer installed."
    systemctl restart "${SERVICE_NAME}.timer" && ok "Timer restarted." || die "Failed."
}

cmd_uninstall() {
    require_root --uninstall
    warn "This removes the push script, cron entry, systemd units, and optionally the config."
    read -rp "Are you sure? (yes/no): " confirm
    [[ "$confirm" == "yes" ]] || { info "Aborted."; exit 0; }
    remove_cron
    remove_systemd_units
    rm -f "$PUSH_SCRIPT"
    read -rp "Also delete config ${CONFIG_FILE}? (yes/no): " del_cfg
    if [[ "$del_cfg" == "yes" ]]; then
        rm -f "$CONFIG_FILE"
        rmdir --ignore-fail-on-non-empty "$CONFIG_DIR" 2>/dev/null || true
        ok "Config deleted."
    else
        info "Config kept at ${CONFIG_FILE}"
    fi
    ok "Uninstall complete."
}

cmd_help() {
    echo
    echo -e "${BOLD}Uptime Kuma push — installer & manager  v${VERSION}${NC}"
    echo
    echo -e "${CYAN}Usage:${NC}"
    echo    "  sudo $0                       First-time install"
    echo    "  sudo $0 --install             Same as above"
    echo    "  sudo $0 --config              Re-run configuration wizard"
    echo    "  sudo $0 --status              Show config and scheduler"
    echo    "  sudo $0 --test                Send one push now"
    echo    "  sudo $0 --start               Enable/start systemd timer"
    echo    "  sudo $0 --stop                Stop systemd timer"
    echo    "  sudo $0 --restart             Restart systemd timer"
    echo    "  sudo $0 --uninstall           Remove everything"
    echo    "       $0 --help                Show this help"
    echo
}

case "${1:-}" in
    ""|--install)  cmd_install   ;;
    --config)      cmd_config    ;;
    --status)      cmd_status    ;;
    --test)        cmd_test      ;;
    --start)       cmd_start     ;;
    --stop)        cmd_stop      ;;
    --restart)     cmd_restart   ;;
    --uninstall)   cmd_uninstall ;;
    --help|-h)     cmd_help      ;;
    *)  error "Unknown option: ${1}"; cmd_help; exit 1 ;;
esac
