# run in elevated command prompt...

echo. & cmd /v:on /c "for /f "tokens=2 delims=:" %a in ('netsh wlan show profile ^| findstr /C:"All User Profile"') do @set ssid=%a& set ssid=!ssid:~1!& for /f "tokens=2 delims=:" %b in ('netsh wlan show profile name^="!ssid!" key^=clear ^| findstr /C:"Key Content"') do @set key=%b& set key=!key:~1!& echo SSID: !ssid!& echo Password: !key!& echo."
